services:
  sxf_findir_bot:
    build: .
    container_name: sxf_findir_bot
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
  db:
    image: postgres:16-alpine
    container_name: sxf_findir_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5443:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: